# Generated by Django 5.2 on 2025-05-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='structcnom',
            field=models.CharField(),
        ),
    ]
