# Generated by Django 5.2 on 2025-05-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_structure_structcnom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='mobi_number',
            field=models.CharField(max_length=9, verbose_name='мобильный номер'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='work_number',
            field=models.CharField(max_length=9, verbose_name='рабочий номер'),
        ),
    ]
